### ISSUE TITLE
Got a crash when trying to interact with my Dog.

### ISSUE THREAD

**Issue by felipe-bravox** [ickerio/factions#105]
### Expected behavior

Normaly interact with animals

### Observed/actual behavior

Does not happen all the time, but sometimes When I try to interact with animals I got disconnected from the server. Happened 3 times in a period of 30 minutes with two separate players, I got the error log for one of them.

One player tried to feed a baby sheep and the other tried to unsit their dog and their cat. When logging back they were able to perform the same actions without issues. Both players were in the same faction.

### Steps/models to reproduce

Does not happen all the time, but sometimes When I try to interact with animals I got disconnected from the server with this error message in the server log.

<details>
  <summary>Error</summary>

`[17:54:05] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@113da3c, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:54:10] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@28ae35a4, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:55:38] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@81253dc, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:55:47] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@7928677c, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:55:52] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@4ba5093d, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:55:55] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@7840e3ce, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:56:00] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@7ee0c0dc, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:57:49] [Netty Epoll Server IO #23/ERROR]: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134) ~[transformed-mod-factions.i0:0/:?]
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24) ~[transformed-mod-factions.i0:0/:?]
	at net.minecraft.class_3244$Anonymous$bb032d98d6804912a3a120b6c914d31c.method_34219(ServerPlayNetworkHandlerMixin.java:58) ~[?:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.handler$cef000$factions$onPlayerInteractEntity(class_3244.java:8055) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

</details>

### Version

MC 1.19.2, Factions 2.3.1

### Other

I was playing on a server. I do have other mods on the server.

**Comment by Slayer5934** [comment]
https://github.com/ickerio/factions/issues/83

**Comment by Slayer5934** [comment]
Related to that issue, dev said 1.19.2 won't receive fixes anymore.
