### ISSUE TITLE
1.19.2 compatibility issue with carrier / carry on

### ISSUE THREAD

**Issue by aloverofwords** [ickerio/factions#83]
When using this mod and either carrier or carry on, attempting to pick up a mob causes the game to crash. Removing the factions mod fixes this problem and mobs can be picked up successfully. 

Failed to handle packet net.minecraft.class_2824@12fbc3c7, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134)
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24)
	at net.minecraft.class_3244$Anonymous$23f6fcca0b034faeae22ab95c7bb85f8.method_34220(ServerPlayNetworkHandlerMixin.java:65)
	at net.minecraft.class_2824$class_5910.method_34213(class_2824.java:146)
	at net.minecraft.class_2824.method_34209(class_2824.java:66)
	at net.minecraft.class_3244.handler$def000$onPlayerInteractEntity(class_3244.java:6055)
	at net.minecraft.class_3244.method_12062(class_3244.java)
	at net.minecraft.class_2824.method_12251(class_2824.java:53)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24515()" because "entity" is null
	at io.icker.factions.core.InteractionManager.onUseEntity(InteractionManager.java:134)
	at io.icker.factions.api.events.PlayerEvents.lambda$static$0(PlayerEvents.java:24)
	at net.minecraft.class_3244$Anonymous$23f6fcca0b034faeae22ab95c7bb85f8.method_34219(ServerPlayNetworkHandlerMixin.java:58)
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116)
	at net.minecraft.class_2824.method_34209(class_2824.java:66)
	at net.minecraft.class_3244.handler$def000$onPlayerInteractEntity(class_3244.java:6055)
	at net.minecraft.class_3244.method_12062(class_3244.java)
	at net.minecraft.class_2824.method_12251(class_2824.java:53)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2535.method_10759(class_2535.java:167)
	at net.minecraft.class_2535.method_10770(class_2535.java:152)
	at net.minecraft.class_2535.channelRead0(class_2535.java:50)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

I have also attached the crash log.

[crash-2022-12-13_21.47.24-client.txt](https://github.com/ickerio/factions/files/10222415/crash-2022-12-13_21.47.24-client.txt)

**Comment by BlueZeeKing** [comment]
We no longer support 1.19.2 so this won't be fixed
